import {
  aboutSummary,
  caseStudies,
  faqItems,
  homePageContent,
  pricingModels,
  pricingSummary,
  privacySummary,
  processSummary,
  profileSummary,
  securitySummary,
  servicePages,
  siteSettings,
  termsSummary,
} from './site-data';

type SeedDocument = Record<string, unknown>;

function slug(value: string) {
  return { _type: 'slug', current: value };
}

export function buildSeedDocuments(): SeedDocument[] {
  return [
    {
      _id: 'globalSettings.main',
      _type: 'globalSettings',
      siteName: siteSettings.name,
      tagline: siteSettings.tagline,
      description: siteSettings.description,
      contactEmail: siteSettings.contactChannels.email,
      lineUrl: siteSettings.contactChannels.line,
      bookingUrl: siteSettings.contactChannels.booking,
      labsUrl: siteSettings.contactChannels.labs,
      navigation: siteSettings.navigation,
      footerNav: siteSettings.footerNav,
      footerUtility: siteSettings.footerUtility,
      brandPillars: siteSettings.brandPillars,
    },
    {
      _id: 'homePage.main',
      _type: 'homePage',
      seo: homePageContent.seo,
      hero: homePageContent.hero,
      fitCases: homePageContent.fitCases,
      notFitNote: homePageContent.notFitNote,
      serviceHighlights: homePageContent.serviceHighlights,
      trustProofs: homePageContent.trustProofs,
      processSteps: homePageContent.processSteps,
      brandSummary: homePageContent.brandSummary,
    },
    {
      _id: 'aboutPage.main',
      _type: 'aboutPage',
      title: aboutSummary.title,
      body: aboutSummary.body,
      seoDescription: aboutSummary.seoDescription,
      principles: aboutSummary.principles,
      boundaries: aboutSummary.boundaries,
    },
    {
      _id: 'profilePage.main',
      _type: 'profilePage',
      title: profileSummary.title,
      body: profileSummary.body,
      seoDescription: profileSummary.seoDescription,
      role: profileSummary.role,
      specialties: profileSummary.specialties,
      workingStyle: profileSummary.workingStyle,
      boundaries: profileSummary.boundaries,
    },
    {
      _id: 'processPage.main',
      _type: 'processPage',
      title: processSummary.title,
      intro: processSummary.intro,
      seoDescription: processSummary.seoDescription,
      steps: processSummary.steps,
    },
    {
      _id: 'pricingPage.main',
      _type: 'pricingPage',
      title: pricingSummary.title,
      seoDescription: pricingSummary.seoDescription,
      intro: pricingSummary.intro,
      factors: pricingSummary.factors,
      proposalItems: pricingSummary.proposalItems,
      models: pricingModels,
    },
    {
      _id: 'securityPage.main',
      _type: 'securityPage',
      title: securitySummary.title,
      seoDescription: securitySummary.seoDescription,
      commitments: securitySummary.commitments,
      intake: securitySummary.intake,
      boundaries: securitySummary.boundaries,
      vendors: securitySummary.vendors,
    },
    {
      _id: 'policyPage.terms',
      _type: 'policyPage',
      title: termsSummary.title,
      eyebrow: termsSummary.eyebrow,
      slug: slug(termsSummary.slug),
      seoTitle: termsSummary.seoTitle,
      seoDescription: termsSummary.seoDescription,
      sections: termsSummary.sections,
    },
    {
      _id: 'policyPage.privacy',
      _type: 'policyPage',
      title: privacySummary.title,
      eyebrow: privacySummary.eyebrow,
      slug: slug(privacySummary.slug),
      seoTitle: privacySummary.seoTitle,
      seoDescription: privacySummary.seoDescription,
      sections: privacySummary.sections,
    },
    ...Object.values(servicePages).map((page) => ({
      _id: `servicePage.${page.key}`,
      _type: 'servicePage',
      serviceKey: page.key,
      title: page.title,
      heroTitle: page.heroTitle,
      heroDescription: page.heroDescription,
      audience: page.audience,
      deliverables: page.deliverables,
      proof: page.proof,
      process: page.process,
      fit: page.fit,
      ctaTitle: page.ctaTitle,
      ctaBody: page.ctaBody,
      seoDescription: page.seoDescription,
    })),
    ...caseStudies.map((item) => ({
      _id: `caseStudy.${item.slug}`,
      _type: 'caseStudy',
      sortOrder: item.sortOrder,
      title: item.title,
      slug: slug(item.slug),
      service: item.service,
      summary: item.summary,
      challenge: item.challenge,
      response: item.response,
      outcomes: item.outcomes,
      proofLabel: item.proofLabel,
    })),
    ...faqItems.map((item) => ({
      _id: `faqItem.${item.slug}`,
      _type: 'faqItem',
      sortOrder: item.sortOrder,
      question: item.question,
      answer: item.answer,
      slug: slug(item.slug),
      service: item.service,
    })),
  ];
}
